model:
  base_learning_rate: 4.5e-6
  target: ldm.models.diffusion.ddpm.PretrainedLatentDiffusion
  params:
    ckpt_path: '{$LOGDIR}logs/LDMI/celebahq-ldm-vq-f4/model.ckpt'    # https://ommer-lab.com/files/latent-diffusion/nitro/cin/config.yaml  
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    image_size: 64
    channels: 3
    monitor: val/total_loss
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 224
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32

    first_stage_config:
      target: ldm.models.autoencoder.IVQModel
      params:
        monitor: "val/rec_loss"
        embed_dim: 3
        n_embed: 8192
        lossconfig:
          target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
          params:
            disc_conditional: false
            disc_in_channels: 3
            disc_start: 20
            disc_weight: 0.75
            codebook_weight: 1.0

        encoder:
          target: ldm.modules.diffusionmodules.model.Encoder
          params:
            attn_type: none
            double_z: false
            z_channels: 3
            resolution: 256
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult:
            - 1
            - 2
            - 4
            num_res_blocks: 2
            attn_resolutions: []
            dropout: 0.0

        decoder:
          target: ldm.modules.decoders.trans_inr.TransInr
          params:
            data_shape: [256, 256]
            update_strategy: scale
            tokenizer:
              target: ldm.modules.decoders.tokenizers.latent_tokenizer.LatentTokenizer
              params:                 # z is (latent_dim, latent_size, latent_size)
                latent_dim: 3         # 3-channel latent tensor
                latent_size: 64       # 16 sized latent tensor  
                patch_size: 4         # Produces 64 tokens (8x8 grid)
                n_head: 4             # 4 attention heads for better feature mixing
                head_dim: 32          # 32 per-head embedding size
            inr:
              target: ldm.modules.decoders.inrs.siren.SIREN
              params:
                in_dim: 2
                out_dim: 3 
                out_bias: 0.5
                depth: 5 
                hidden_dim: 256
            n_groups: 128   # in Trans-INR CelebA: 64
            transformer:
              target: ldm.modules.decoders.transformer.Transformer
              params:
                dim: 384  # Increased from 320 to 384
                encoder_depth: 5  # Increased from 4 to 5
                decoder_depth: 5  # Increased from 4 to 5
                n_head: 6  # Increased from 5 to 6
                head_dim: 64  # Adjusted to match dim=384 (6 × 64 = 384)
                ff_dim: 1536  # Increased from 1280 to 1536
                dropout: 0.1

        data_converter:
          target:  ldm.data.data_converters.conversion.ImageResize
          params:
            size: 256

    cond_stage_config: __is_unconditional__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 8
    wrap: false
    train:
      target: ldm.data.celebahq.CelebAHQ
      params:
        size: 256
        data_root: /work3/ipeaz/data/celebahq/train/

    validation:
      target:  ldm.data.celebahq.CelebAHQ
      params:
        size: 256
        data_root: /work3/ipeaz/data/celebahq/val/


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        disabled: True
        batch_frequency: 50000
        max_images: 12
        cols: 6
        increase_log_steps: False
        log_first_step: False

  trainer:
    #precision: bf16  # Best for H100
    max_epochs: -1  # Infinite epochs
    benchmark: True