model:
  base_learning_rate: 1.0e-6
  target: ldm.models.diffusion.ddpm.PretrainedLatentDiffusion
  params:
    ckpt_path: '{$LOGDIR}logs/LDMI/cin-ldm-vq-f4/model.ckpt'    # https://ommer-lab.com/files/latent-diffusion/nitro/cin/
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: class_label
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/total_loss    
    use_ema: False

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 192
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_heads: 1
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512


    first_stage_config:
      target: ldm.models.autoencoder.IVQModel
      params:
        monitor: "val/rec_loss"
        embed_dim: 3
        n_embed: 8192
        lossconfig:
          target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
          params:
            disc_conditional: false
            disc_in_channels: 3
            disc_start: 1     
            disc_weight: 0.75
            codebook_weight: 1.0

        encoder:
          target: ldm.modules.diffusionmodules.model.Encoder
          params:
            double_z: false
            z_channels: 3
            resolution: 256
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult:
            - 1
            - 2
            - 4
            num_res_blocks: 2
            attn_resolutions: []
            dropout: 0.0

        decoder:
          target: ldm.modules.decoders.trans_inr.TransInr
          params:
            data_shape: [256, 256]
            update_strategy: scale
            tokenizer:
              target: ldm.modules.decoders.tokenizers.latent_tokenizer.LatentTokenizer
              params:                 # z is (latent_dim, latent_size, latent_size)
                latent_dim: 3         # 3-channel latent tensor
                latent_size: 64       # 16 sized latent tensor  
                patch_size: 4         
                n_head: 4             # 4 attention heads for better feature mixing
                head_dim: 32          # 32 per-head embedding size

            inr:
              target: ldm.modules.decoders.inrs.siren.SIREN
              params:
                in_dim: 2
                out_dim: 3 
                out_bias: 0.5
                depth: 5 
                hidden_dim: 256
                
            n_groups: 128   # in Trans-INR CelebA: 64
            transformer:
              target: ldm.modules.decoders.transformer.Transformer
              params:
                dim: 768 
                encoder_depth: 6 
                decoder_depth: 6  
                n_head: 12 
                head_dim: 64 
                ff_dim: 3072  

    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        n_classes: 1001
        embed_dim: 512
        key: class_label

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 8
    wrap: false
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
        data_root: '{$LOGDIR}data/imagenet/'
    validation:
      target:  ldm.data.imagenet.ImageNetValidation
      params:
        data_root: '{$LOGDIR}data/imagenet/'


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 100000
        max_images: 9
        increase_log_steps: False
        log_first_step: False

  trainer:
    max_epochs: -1  # Infinite epochs
    benchmark: True