name: ldmi
channels:
  - nvidia
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - pytorch=2.4.1
  - torchvision=0.19.1
  - numpy=1.19.2
  - pytorch-cuda=12.1
  - pip:
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.9.5
    - torchmetrics==0.7.0
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.3.1
    - pillow==9.5.0
    - wandb==0.19.4
    - tensorboardX==2.6.2.2
    - matplotlib==3.6.2
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .