model:
  base_learning_rate: 3.0e-6
  target:  ldm.models.autoencoder.IPVAE
  params:
    monitor: "val/rec_loss"
    lossconfig:
      target:  ldm.modules.losses.occupancy_loss.BernoulliLoss
      params:
        kl_weight: 1.0e-4

    encoder:
      target: ldm.modules.encoders.conv3d_encoder.Conv3DEncoder
      params:
        dim_z: 32
        base_channels: 64
        dropout: 0.1

    decoder:
      target: ldm.modules.decoders.hyper_mlp.HyperMLP
      params:
        data_shape: [32, 32, 32]
        update_strategy: scale
        tokenizer:
          target: ldm.modules.decoders.tokenizers.latent_tokenizer.LatentTokenizer
          params:                 # z is (latent_dim, latent_size, latent_size)
            latent_dim: 32        # latent depth is doubled in post_quant_conv
            latent_size: [8,8]    # 16 sized latent tensor  
            patch_size: 1         # Produces 64 tokens (8x8 grid)
            n_head: 4             # 4 attention heads for better feature mixing
            head_dim: 48     # ↑ from 32 → higher expressiveness

        inr:
          target: ldm.modules.decoders.inrs.inr_mlp.InrMlp
          params:
            in_dim: 3
            out_dim: 1 
            out_bias: 0.5
            depth: 3
            hidden_dim: 128
            use_pe: true
            pe_dim: 128

        n_groups: 128  # Using the same as original
        mlp:
          target: ldm.modules.decoders.mlp.MLP
          params:
            hidden_dims: [128, 256, 512]
            dropout: 0.1  # Same as original
            activation: 'gelu'


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 8
    wrap: false
    train:
      target: ldm.data.pointcloud.VoxelTrain
      params:
        data_root: /work3/ipeaz/data/
    validation:
      target:  ldm.data.pointcloud.VoxelVal
      params:
        data_root: /work3/ipeaz/data/
    test:
      target:  ldm.data.pointcloud.VoxelTest
      params:
        data_root: /work3/ipeaz/data/

lightning:
  callbacks:
    image_logger:
      target: main.VoxelLogger
      params:
        batch_frequency: 1000
        max_images: 16
        cols: 4
        increase_log_steps: False
        clamp: True
        log_first_step: True

  trainer:
    max_epochs: -1
    benchmark: True
    gradient_clip_val: null
